# Breasts cancer classification

<img src='./cancer.JPG'>

In [18]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

from sklearn import linear_model     # linear_model.LogisticRegression
from sklearn import model_selection  # model_selection.train_test_split
from sklearn import metrics          # metrics.accuracy_score
from sklearn import preprocessing    # preprocessing.StandardScaler
from sklearn import datasets         # datasets.load_breasts_cancer
%matplotlib inline

### Load data

In [19]:
data = datasets.load_breast_cancer()  # sklearn.utils.Bunch
print(data.DESCR)

Breast Cancer Wisconsin (Diagnostic) Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, field
        13 is Radius SE, field 23 is Worst Radius.

        

In [20]:
x = data.data    # (569, 30)
y = data.target  # (569,)

In [21]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [22]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [23]:
x = pd.DataFrame(x, columns=data.feature_names)

In [25]:
display(x.head())
display(y[0:5])

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension           ...             worst radius  \
0                 0.07871           ...                    25.38   
1                 0.05667           ...                    24.99   
2                 0.05999           ...                    23.57   
3                 0.09744           ...                    14.91   
4                 0.05883           ...                    22.54   

   worst texture  worst perimeter  worst area  worst smoothness  \
0          17.33           184.60      2019.0            0.1622   
1          23.41           158.80      1956.0            0.1238   
2          25.53           152.50      1709.0            0.1444   
3          26.50            98.87       567.7            0.2098   
4          16.67           152.20      1575.0            0.1374   

   worst compactness  worst concavity  worst concave points  worst symmetry  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   worst fractal dimension  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 30 columns]

array([0, 0, 0, 0, 0])

### Data analysis

In [26]:
#pd.DataFrame.hist(x, figsize=(16,16))
#plt.show()

In [27]:
#pd.DataFrame.hist(y, figsize=(5,5))
#plt.show()

In [28]:
#plt.figure(figsize=(12, 12))
#plt.xticks(np.arange(0, x.shape[1]), data.feature_names, rotation=90)  # Names drop fix need
#plt.yticks(np.arange(0, x.shape[1]), data.feature_names)
#plt.imshow(pd.DataFrame.corr(x), cmap='ocean')
#plt.colorbar()
#plt.show()

### Split data and Preprocessing

In [29]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, train_size=0.67, test_size=0.33, \
                                                                    stratify=y, random_state=7)

In [30]:
scaler = preprocessing.StandardScaler()
scaler.fit(x_train, y_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

### Logistic Regression Model

In [31]:
r = linear_model.LogisticRegression()

In [32]:
r.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
r.intercept_

array([0.26862964])

In [34]:
r.coef_

array([[-0.27544023, -0.50084558, -0.29832841, -0.44222808, -0.08345319,
         0.47774684, -0.64537462, -0.58458543, -0.19299068,  0.27567901,
        -1.09019124,  0.18326243, -0.5666638 , -0.91496324, -0.0730358 ,
         0.81075687, -0.14531782, -0.40100136,  0.26422463,  0.43892385,
        -0.95668819, -1.14486767, -0.75504657, -1.00071393, -0.58473687,
         0.08872894, -0.72647006, -0.89528128, -0.69997844, -0.6512288 ]])

### Evaluation of our model

In [35]:
y_predicted = r.predict(x_train)

In [36]:
metrics.accuracy_score(y_train, y_predicted)  # Accuracy on train set

0.989501312335958

In [37]:
y_predicted = r.predict(x_test)

In [38]:
metrics.accuracy_score(y_test, y_predicted)  # Accuracy on train set

0.9787234042553191

In [39]:
r.predict_proba(x_test)  # Probability estimates.
                         # The returned estimates for all classes are ordered by the label of classes.
                         # For a multi_class problem, if multi_class is set to be "multinomial" the softmax 
                         # function is used to find the predicted probability of each class.
                         # Else use a one-vs-rest approach, i.e calculate the probability
                         # of each class assuming it to be positive using the logistic function.
                         # and normalize these values across all the classes.

array([[3.51830920e-01, 6.48169080e-01],
       [2.67301413e-02, 9.73269859e-01],
       [2.66651128e-03, 9.97333489e-01],
       [4.22426881e-05, 9.99957757e-01],
       [9.99993867e-01, 6.13331626e-06],
       [6.87209340e-03, 9.93127907e-01],
       [3.60896810e-05, 9.99963910e-01],
       [9.96715900e-01, 3.28409968e-03],
       [1.66967960e-01, 8.33032040e-01],
       [2.26315688e-04, 9.99773684e-01],
       [1.00000000e+00, 5.42966397e-11],
       [2.84485196e-03, 9.97155148e-01],
       [9.99998045e-01, 1.95480380e-06],
       [3.03638622e-02, 9.69636138e-01],
       [9.99998462e-01, 1.53828628e-06],
       [2.37469623e-02, 9.76253038e-01],
       [1.16842203e-03, 9.98831578e-01],
       [1.13550769e-02, 9.88644923e-01],
       [9.99990219e-01, 9.78120110e-06],
       [1.79590218e-02, 9.82040978e-01],
       [7.36991011e-02, 9.26300899e-01],
       [6.75467623e-04, 9.99324532e-01],
       [9.99999999e-01, 1.17783890e-09],
       [1.87824315e-04, 9.99812176e-01],
       [4.986285

### Build final models for real use

In [40]:
r = r.fit(x, y)  # Final model

In [41]:
t = np.random.randn(x.shape[1])
t

array([ 0.21247418, -1.28325764, -1.55309015, -0.36863766,  0.57166924,
        0.79989438, -0.70349591, -0.69121242,  0.33784808, -0.73299989,
       -0.01813769, -0.00284682, -0.04213027, -0.61169704, -0.49498158,
       -0.33122912,  1.06938594,  0.0480157 , -1.17302208,  0.23007159,
        0.73208151,  2.53497631, -0.03156339, -0.50774675,  0.38172782,
        0.72745906, -0.52948822,  1.6713795 ,  0.05999983, -1.48550781])

In [42]:
r.predict(t.reshape(1, -1))

array([1])

In [43]:
r.predict_proba(t.reshape(1, -1))

array([[0.47220053, 0.52779947]])